### ISSUE TITLE
Why should I use ember-promise?

### ISSUE THREAD

**Issue by antulik** [toranb/ember-promise#6]
Hi, I'm new to ember, so that question might sound stupid.

After reading blogs and readme, I still don't understand what is the value in ember-promise. What are the benefits of wrapping xhr with ember.run?

**Comment by toranb** [comment]
The quick version has 2 answers

1) without an explicit run-loop async code will be executed inside an "auto run" meaning that the behavior is non deterministic (it's possible you will find a funny behavior in some callback and not know why/ or be able to (easily) trace it down)

2) in your tests anything that uses this would fail because in testing land any "auto run" blows up (causing a failure in qunit). In my experience this is a good thing -helps me catch places I should have an explicit ember.run (but forgot about).

The long answer (more details if you want to look at the theory/ how the run-loop actually works)

http://www.programwitherik.com/why-you-should-care-about-the-ember-run-loop/

**Comment by antulik** [comment]
Thanks, for some reasons I did expect Ember.$.ajax to automatically do this as it's a required behaviour and surprised to see it's not the case.

**Comment by toranb** [comment]
Great point - the Ember.$.ajax is truly just a global wrapped $.ajax (no ember magic injected). Sorry I didn't call this out first (losing my beginners mind it seems).

Thanks for writing!
